<?php
/** @var Theme\Element\Output\Html\Template  $this */
?><!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->get('head') ?>
</head>
<body>
<?php echo $this->get('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->get('global_notices') ?>
    <div class="page">
        <?php echo $this->get('header') ?>
        <div class="main-container col3-layout">
            <div class="main">
                <?php echo $this->get('breadcrumbs') ?>
                <div class="col-wrapper">
                    <div class="col-main">
                        <?php echo $this->get('global_messages') ?>
                        <?php echo $this->get('content') ?>
                    </div>
                    <div class="col-left sidebar"><?php echo $this->get('left') ?></div>
                </div>
                <div class="col-right sidebar"><?php echo $this->get('right') ?></div>
            </div>
        </div>
        <?php echo $this->get('footer') ?>
        <?php echo $this->get('global_cookie_notice') ?>
        <?php echo $this->get('before_body_end') ?>
    </div>
</div>
</body>
</html>
